INSERT INTO sms_templates (id, code, body)
VALUES (gen_random_uuid(), 'SAFE_HARVEST_NOTICE',
        'Habari {{name}}. Your {{crop}} is now safe to harvest. Reply WASTE to schedule pickup or dial *XXX# > 3. - ZaoCycle'),
       (gen_random_uuid(), 'PICKUP_SCHEDULED_FARMER',
        'Pickup scheduled for {{date}}. Have your farm waste ready by the road. - ZaoCycle'),
       (gen_random_uuid(), 'PICKUP_REMINDER_FARMER',
        'Reminder: waste pickup tomorrow {{date}}. Have farm waste ready. - ZaoCycle'),
       (gen_random_uuid(), 'PICKUP_ASSIGNED_RIDER',
        'New pickup: {{farmerName}} at {{ward}}, scheduled {{date}}. View in app. - ZaoCycle'),
       (gen_random_uuid(), 'PAYOUT_CONFIRMATION',
        'KSh {{amount}} sent to {{phone}} for {{kg}}kg waste. Tx: {{txId}}. - ZaoCycle'),
       (gen_random_uuid(), 'ORDER_PAID_BUYER',
        'Order #{{orderId}} confirmed. {{kg}}kg briquettes, KSh {{amount}}. Delivery {{date}}. - ZaoCycle'),
       (gen_random_uuid(), 'ORDER_PAID_OPS',
        'New paid order: {{kg}}kg from {{buyerName}}. Order #{{orderId}}. - ZaoCycle'),
       (gen_random_uuid(), 'NOT_REGISTERED',
        'Sorry, your number is not registered on ZaoCycle. Dial *XXX# to register. - ZaoCycle'),
       (gen_random_uuid(), 'UNKNOWN_COMMAND',
        'Sorry, command not recognized. Reply WASTE to schedule pickup, BAL for balance, or dial *XXX# for menu. - ZaoCycle');
