INSERT INTO chemicals (id, name, active_ingredient, category, half_life_days, phi_days, common_crops, active)
VALUES (gen_random_uuid(), 'Ridomil Gold MZ', 'Metalaxyl-M + Mancozeb', 'FUNGICIDE', 7, 7, 'Tomatoes,Potatoes', true),
       (gen_random_uuid(), 'Karate 2.5 EC', 'Lambda-cyhalothrin', 'INSECTICIDE', 5, 7, 'Tomatoes,French Beans,Cabbage',
        true),
       (gen_random_uuid(), 'Dudu Acelegold', 'Acetamiprid + Lambda-cyhalothrin', 'INSECTICIDE', 7, 14,
        'Tomatoes,Onions', true),
       (gen_random_uuid(), 'Roundup', 'Glyphosate', 'HERBICIDE', 14, 21, 'Pre-planting', true),
       (gen_random_uuid(), 'Milraz', 'Cymoxanil + Propineb', 'FUNGICIDE', 7, 14, 'Tomatoes,Potatoes', true),
       (gen_random_uuid(), 'Dithane M-45', 'Mancozeb', 'FUNGICIDE', 3, 7, 'Tomatoes,Potatoes,Cabbage,Onions', true),
       (gen_random_uuid(), 'Curzate M8', 'Cymoxanil + Mancozeb', 'FUNGICIDE', 7, 7, 'Tomatoes,Potatoes', true),
       (gen_random_uuid(), 'Actara 25 WG', 'Thiamethoxam', 'INSECTICIDE', 14, 14, 'Tomatoes,French Beans', true),
       (gen_random_uuid(), 'Confidor 70 WG', 'Imidacloprid', 'INSECTICIDE', 21, 21, 'Tomatoes,Cabbage,Onions', true),
       (gen_random_uuid(), 'Decis 2.5 EC', 'Deltamethrin', 'INSECTICIDE', 5, 7, 'Tomatoes,French Beans,Cabbage', true),
       (gen_random_uuid(), 'Ortiva', 'Azoxystrobin', 'FUNGICIDE', 7, 7, 'Tomatoes,Potatoes,Onions', true),
       (gen_random_uuid(), 'Score 250 EC', 'Difenoconazole', 'FUNGICIDE', 14, 14, 'Tomatoes,Potatoes', true),
       (gen_random_uuid(), 'Acrobat MZ', 'Dimethomorph + Mancozeb', 'FUNGICIDE', 7, 7, 'Tomatoes,Potatoes', true),
       (gen_random_uuid(), 'Ekondoplus', 'Profenofos + Cypermethrin', 'INSECTICIDE', 7, 14,
        'Tomatoes,French Beans,Cabbage', true),
       (gen_random_uuid(), 'Kingcode Elite 50EC', 'Cypermethrin + Chlorpyrifos', 'INSECTICIDE', 14, 21,
        'Tomatoes,Cabbage', true),
       (gen_random_uuid(), 'Lexus 247 SC', 'Fluazifop-P-butyl', 'HERBICIDE', 7, 14, 'Tomatoes,French Beans', true),
       (gen_random_uuid(), 'Trophy 480 EC', 'Acetochlor', 'HERBICIDE', 14, 21, 'Pre-emergence', true),
       (gen_random_uuid(), 'Sulcop 50 WP', 'Copper Oxychloride', 'FUNGICIDE', 3, 7, 'Tomatoes,Potatoes,Cabbage', true),
       (gen_random_uuid(), 'Biodine 7.5 WDG', 'Indoxacarb', 'INSECTICIDE', 7, 7, 'Tomatoes,French Beans', true),
       (gen_random_uuid(), 'Avaunt 150 SC', 'Indoxacarb', 'INSECTICIDE', 7, 14, 'Tomatoes,Cabbage', true),
       (gen_random_uuid(), 'Coragen 20 SC', 'Chlorantraniliprole', 'INSECTICIDE', 14, 1, 'Tomatoes,French Beans', true),
       (gen_random_uuid(), 'Folicur 250 EW', 'Tebuconazole', 'FUNGICIDE', 14, 21, 'Onions,Tomatoes', true),
       (gen_random_uuid(), 'Clorpyrifos 480 EC', 'Chlorpyrifos', 'INSECTICIDE', 21, 21, 'Potatoes,Cabbage', true),
       (gen_random_uuid(), 'Ranman 400 SC', 'Cyazofamid', 'FUNGICIDE', 7, 7, 'Potatoes,Tomatoes', true),
       (gen_random_uuid(), 'Mospilan 20 SP', 'Acetamiprid', 'INSECTICIDE', 7, 14, 'Tomatoes,French Beans,Cabbage',
        true);
